security:

    # Les encodeurs disponibles pour les types d'utilisateurs du système
    encoders: 
        # plaintext = en clair / auto = prend le meilleur disponible sur le système
        # en 2021 soit bcrypt soit argon2
        Symfony\Component\Security\Core\User\User: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    # Endroits où peuvent se trouver nos utilisateurs
    providers:
        # Nom du provider
        users_in_memory: 
            # En mémoire (dans ce fichier)
            memory: 
                # Petit nom pour la liste de nos utilisateurs
                users:
                    # Identifiant d'un utilisateur
                    user1:
                        # Mot de passe (en clair)
                        password: '$argon2id$v=19$m=65536,t=4,p=1$kEBSt2xHBjfz+iaqtRF1VQ$N1mFTpFkfcXptob51gL1eZUgGxAel+DtLiZsR3j2NhY' #user
                        # Liste (array) de rôles
                        roles: ['ROLE_USER']
                        # Identifiant d'un utilisateur
                    admin1:
                        # Mot de passe (en clair)
                        password: '$argon2id$v=19$m=65536,t=4,p=1$HjfUC3HLaM6Sozh0kSoCfg$/gSXh2i2rvd/fA9hbdtqR6Ioh1snY5N5N8CsypLAJP0' # admin
                        # Liste (array) de rôles
                        roles: ['ROLE_ADMIN']
    # Les firewalls sont un ensemble de règles de sécurité
    # qui régissent le fonctionnement de la sécurité de notre appli
    firewalls:
        # Le firewall de "dev"
        # permet de désactiver la sécurité les URLs du Profiler
        # et de la Web Debug Toolbar et des dossiers d'assets
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # Notre firewall princpal 
        main:
            # Anonyme autorisé
            anonymous: true
            # Session User démarrée que si on cherche à se connecter
            lazy: true
            # Où sont les utilisateurs ?
            provider: users_in_memory

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # Authentification via "HTTP BASIC"
            http_basic: true 

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

            # Déconnexion 
            logout:
                # Soit un chemin (endpoint, /logout), soit un nom de route
                path: user_logout

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # /admin correspond à mon lien admin du MainController
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/review/add, roles: ROLE_USER }
